"""
build_report.py — summary.json(요약) + results.json(원시 데이터)를 읽어
스타일이 입혀진 report.html 과 report.md 를 생성한다.

- HTML: 자체 포함(self-contained) CSS. 브라우저에서 열고 Ctrl+P -> "PDF로 저장" 하면 PDF.
- MD:  깔끔한 한 장짜리 마크다운.

요약(summary.json)은 Claude Code 가 생성하고, 이 스크립트는 렌더링만 담당한다.
표준 라이브러리만 사용 — 설치 불필요.

사용법:
    python build_report.py
    python build_report.py --summary summary.json --out report
"""

import json
import html
import argparse

CSS = """
:root { --ink:#1a2330; --muted:#5b6b7d; --line:#e3e8ef; --accent:#1f6feb;
        --warn-bg:#fff7ed; --warn-bd:#f59e0b; --chip:#eef4ff; }
* { box-sizing: border-box; }
body { font-family: -apple-system, "Segoe UI", "Malgun Gothic", sans-serif;
       color: var(--ink); line-height: 1.6; max-width: 820px; margin: 0 auto;
       padding: 40px 32px; background:#fff; }
header { border-bottom: 3px solid var(--accent); padding-bottom: 16px; margin-bottom: 24px; }
h1 { font-size: 1.6rem; margin: 0 0 4px; }
.subtitle { color: var(--muted); font-size: .85rem; }
h2 { font-size: 1.05rem; margin: 28px 0 12px; padding-left: 10px;
     border-left: 4px solid var(--accent); }
.kv { display: grid; grid-template-columns: 120px 1fr; gap: 6px 14px;
      font-size: .92rem; }
.kv dt { color: var(--muted); font-weight: 600; }
.kv dd { margin: 0; }
.warn { background: var(--warn-bg); border-left: 4px solid var(--warn-bd);
        padding: 12px 16px; border-radius: 6px; margin: 10px 0; }
.warn ul { margin: 6px 0 0; padding-left: 18px; }
.warn li { margin: 3px 0; font-size: .9rem; }
.callout { background:#f1f6ff; border:1px solid #d6e4ff; border-radius:8px;
           padding:14px 18px; font-size:.95rem; }
.paper { border:1px solid var(--line); border-radius:10px; padding:16px 18px;
         margin:12px 0; }
.paper h3 { margin:0 0 6px; font-size: 1rem; }
.meta { font-size:.78rem; color:var(--muted); margin-bottom:10px; }
.chip { display:inline-block; background:var(--chip); color:var(--accent);
        border-radius:999px; padding:2px 10px; font-size:.72rem; font-weight:600;
        margin-right:6px; }
.field { font-size:.9rem; margin:4px 0; }
.field b { color: var(--accent); }
footer { margin-top:32px; padding-top:14px; border-top:1px solid var(--line);
         color:var(--muted); font-size:.78rem; }
a { color: var(--accent); text-decoration: none; }
@media print { body { padding: 0; } .paper { break-inside: avoid; } }
"""


def esc(x):
    return html.escape(str(x or ""))


def build_html(s, sources):
    papers_html = ""
    for i, p in enumerate(s["papers"], 1):
        link = ""
        pmid = p.get("pmid")
        if pmid:
            link = f' · <a href="https://pubmed.ncbi.nlm.nih.gov/{esc(pmid)}/">PMID {esc(pmid)}</a>'
        papers_html += f"""
    <div class="paper">
      <h3>{i}. {esc(p['title'])}</h3>
      <div class="meta">{esc(p.get('journal',''))} ({esc(p.get('year',''))}){link}</div>
      <div class="field"><b>목적</b> · {esc(p.get('purpose',''))}</div>
      <div class="field"><b>결과</b> · {esc(p.get('result',''))}</div>
      <div class="field"><b>안전성</b> · {esc(p.get('safety',''))}</div>
    </div>"""

    warnings_html = "".join(f"<li>{esc(w)}</li>" for w in s["fda_summary"]["warnings"])

    return f"""<!doctype html>
<html lang="ko"><head><meta charset="utf-8">
<title>약물 정보 보고서 — {esc(s['drug'])}</title>
<style>{CSS}</style></head>
<body>
  <header>
    <h1>약물 정보 요약 보고서</h1>
    <div class="subtitle">{esc(s['drug'])} &nbsp;·&nbsp; 데이터 소스: {esc(sources)}</div>
  </header>

  <h2>핵심 메시지</h2>
  <div class="callout">{esc(s['key_message'])}</div>

  <h2>허가 정보 (FDA)</h2>
  <dl class="kv">
    <dt>적응증</dt><dd>{esc(s['fda_summary']['indications'])}</dd>
    <dt>용법·용량</dt><dd>{esc(s['fda_summary']['dosage'])}</dd>
  </dl>
  <div class="warn"><b>⚠ 주요 경고</b><ul>{warnings_html}</ul></div>

  <h2>최신 논문 요약 ({len(s['papers'])}건)</h2>
  {papers_html}

  <footer>{esc(s['generated_note'])}<br>
  Generated by mini-project drug report tool · 논문 전문 분석·통계 재검증은 범위 외.</footer>
</body></html>"""


def build_md(s, sources):
    lines = [
        f"# 약물 정보 요약 보고서: {s['drug']}",
        "",
        f"> 데이터 소스: {sources}",
        "",
        "## 핵심 메시지",
        s["key_message"],
        "",
        "## 허가 정보 (FDA)",
        f"- **적응증**: {s['fda_summary']['indications']}",
        f"- **용법·용량**: {s['fda_summary']['dosage']}",
        "",
        "**⚠ 주요 경고**",
    ]
    lines += [f"- {w}" for w in s["fda_summary"]["warnings"]]
    lines += ["", f"## 최신 논문 요약 ({len(s['papers'])}건)", ""]
    for i, p in enumerate(s["papers"], 1):
        pmid = f" — PMID {p['pmid']}" if p.get("pmid") else ""
        lines += [
            f"### {i}. {p['title']} ({p.get('journal','')}, {p.get('year','')}){pmid}",
            f"- **목적**: {p.get('purpose','')}",
            f"- **결과**: {p.get('result','')}",
            f"- **안전성**: {p.get('safety','')}",
            "",
        ]
    lines += ["---", f"*{s['generated_note']}*"]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description="요약 -> 스타일 보고서(HTML+MD) 렌더러")
    ap.add_argument("--summary", default="summary.json")
    ap.add_argument("--results", default="results.json")
    ap.add_argument("--out", default="report", help="출력 파일 이름(확장자 제외)")
    args = ap.parse_args()

    with open(args.summary, encoding="utf-8") as f:
        s = json.load(f)

    sources = "PubMed (E-utilities), openFDA"
    try:
        with open(args.results, encoding="utf-8") as f:
            r = json.load(f)
        sources += f" · 검색어: {r.get('drug_resolved', '')}"
    except FileNotFoundError:
        pass

    with open(f"{args.out}.html", "w", encoding="utf-8") as f:
        f.write(build_html(s, sources))
    with open(f"{args.out}.md", "w", encoding="utf-8") as f:
        f.write(build_md(s, sources))

    print(f"[+] 생성: {args.out}.html  (브라우저에서 열고 Ctrl+P -> PDF로 저장)")
    print(f"[+] 생성: {args.out}.md")


if __name__ == "__main__":
    main()
